---
# tasks file for httpd
#
- name: install httpd for ubuntu
  ansible.builtin.apt:
    name: apache2
    state: present

- name: start and enable httpd
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: copy index.html to webservers
  ansible.builtin.copy:
    src: hello.html
    dest: /var/www/html/

- name: reconfigure port number
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: 
  - restart httpd 
...
