---
# tasks file for httpd
#
- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: installed

- name: start and enable httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: copy index.html to webservers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/html/
  loop:
    - index.html
    - alpha.html
    - beta.html
    - gama.html

- name: reconfigure port number
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: 
  - restart httpd 
...
